include: package:flutter_lints/flutter.yaml

analyzer:
  exclude: [ build/** ]
  language:
    strict-raw-types: true
  strong-mode:
    implicit-casts: false
    implicit-dynamic: false
  errors:
    invalid_assignment: warning
    missing_return: error
    dead_code: warning

linter:
  rules:
    unnecessary_statements: true
    avoid_type_to_string: true
    avoid_print: true
    prefer_single_quotes: true
    always_declare_return_types: true
    cancel_subscriptions: true
    close_sinks: true
    only_throw_errors: true
    sort_child_properties_last: true
    always_put_required_named_parameters_first: true
    always_specify_types: true
    avoid_double_and_int_checks: true
    avoid_multiple_declarations_per_line: true
    avoid_positional_boolean_parameters: true
    cast_nullable_to_non_nullable: true
    deprecated_consistency: true
    do_not_use_environment: true
    directives_ordering: true
    eol_at_end_of_file: true
    no_runtimeType_toString: true
    parameter_assignments: true
    prefer_final_in_for_each: true
    prefer_final_locals: true
    prefer_if_elements_to_conditional_expressions: true
    prefer_null_aware_method_calls: true
    sort_unnamed_constructors_first: true
    unnecessary_await_in_return: true
    unnecessary_constructor_name: true
    unnecessary_lambdas: true
    unnecessary_parenthesis: true
    unnecessary_raw_strings: true
    use_is_even_rather_than_modulo: true
    use_named_constants: true
