name: flutter_basic
description: A personalised boilerplate for Flutter Apps

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^0.13.3
  rxdart: ^0.27.2
  package_info_plus: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  flutter_launcher_icons: ^0.9.2

flutter_icons:
  image_path_android: "assets/logo.jpg"
  image_path_ios: "assets/logo.jpg"
  android: true
  ios: true

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/logo.jpg
    - assets/fonts/

  fonts:
    - family: FontAwesome
      fonts:
        - asset: assets/fonts/FA6-Regular.otf
          weight: 400
        - asset: assets/fonts/FA6-Solid.otf
          weight: 900
    - family: FontAwesomeBrands
      fonts:
        - asset: assets/fonts/FA6-Brands.otf
          weight: 400
